---

name: mysway
description: Minimal Sway build that suits my needs.

base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - type: dnf
    repos:
      copr:
        - erikreider/swayosd
    install:
      packages:
        # --- GRAPHICS ---
        - libva-utils
        - mesa-dri-drivers
        - mesa-va-drivers
        - mesa-vulkan-drivers
        - vulkan-loader
        
        # --- SOUND ---
        - pipewire
        - pipewire-pulseaudio
        - wireplumber

        # --- HARDWARE ---
        - i2c-tools
        - NetworkManager
        - openrgb
        - openrgb-udev-rules
        - solaar
        - steam-devices

        # --- SECURITY
        - policycoreutils
        - selinux-policy-targeted

        # --- FLATPAK
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-wlr
        
        # --- DISPLAY MANAGER ---
        - sddm
        - sddm-wayland-sway
        
        # --- WINDOW MANAGER ---
        - sway
        - fuzzel
        - jq
        - mako
        - py3status
        - swaybg
        - swayidle
        - swaylock
        - swayosd
        - wl-clipboard
        - xorg-x11-server-Xwayland

        # --- TERMINAL
        - foot
        - bat
        - dash
        - eza
        - fastfetch
        - fd-find
        - file
        - fzf
        - inxi
        - progress
        - ripgrep
        - starship
        - tldr
        - trash-cli
        - zoxide
        - zsh
        - util-linux-user # Needed to change the shell to zsh
        
        # --- FONTS
        - jetbrains-mono-fonts-all

        # --- UTILS ---
        - aria2
        - bc
        - distrobox
        - gdisk
        - htop
        - mpv
        - mupdf
        - nmap
        - swayimg
        - unar
        - unzip
        - usbutils
        - wev
        - wordgrinder
        
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.github.Matoking.protontricks
          - com.github.tchx84.Flatseal
          - io.github.wivrn.wivrn
          - io.gitlab.librewolf-community
          - com.valvesoftware.Steam
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
      - scope: user

  - type: script
    snippets:
      # Set zsh as default shell
      - sed -i 's/SHELL=\/bin\/bash/SHELL=\/usr\/bin\/zsh/' /etc/default/useradd
      - sed -i 's|/bin/bash$|/usr/bin/zsh|' /etc/passwd
      - grep -q '/usr/bin/zsh' /etc/shells || echo '/usr/bin/zsh' >> /etc/shells
      
      - "systemctl enable sddm.service"
      - "systemctl enable NetworkManager.service"
      - "systemctl set-default graphical.target"
      - "systemctl enable swayosd-libinput-backend.service"
      - "systemctl --global enable pipewire.socket"
      - "systemctl --global enable wireplumber.service"
 
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
