---

name: mysway
description: Minimal Sway build that suits my needs.

base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: kargs
    arch: x86_64
    kargs:
      - loglevel=3
      
      # Disables flashing cursor in tty
      - fbcon=nodefer
      - vt.global_cursor_default=0
      
      - systemd.unit=multi-user.target
      - video=DP-1:3440x1440@174.002
      - consoleblank=60
      - grub.timeout=0
      - grub.timeout_style=hidden

  - type: dnf
    install:
      packages:
        # --- GRAPHICS ---
        - libva-utils
        - mesa-dri-drivers
        - mesa-va-drivers
        - mesa-vulkan-drivers
        - vulkan-loader
        # --- SOUND ---
        - pipewire
        - pipewire-pulseaudio
        - wireplumber
        # --- HARDWARE ---
        - i2c-tools
        - NetworkManager
        - openrgb
        - openrgb-udev-rules
        - solaar
        - steam-devices
        # --- SECURITY ---
        - policycoreutils
        - selinux-policy-targeted
        # --- FLATPAK ---
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-wlr
        # --- WINDOW MANAGER ---
        - sway
        - brightnessctl
        - fuzzel
        - python-i3ipc
        - jq
        - mako
        - py3status
        - swaybg
        - swayidle
        - swaylock
        - wlsunset
        - wl-clipboard
        - wob
        - xorg-x11-server-Xwayland
        # --- TERMINAL ---
        - foot
        - 7zip
        - bashmount
        - bat
        - chafa
        - dash
        - eza
        - fastfetch
        - fd-find
        - ffmpegthumbnailer
        - file
        - fzf
        - ImageMagick
        - inxi
        - neovim
        - poppler-utils
        - progress
        - ripgrep
        - tldr
        - trash-cli
        - zoxide
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - util-linux-user # Needed to change the shell to zsh
        # --- UTILS ---
        - aria2
        - bc
        - btop
        - distrobox
        - gdisk
        - htop
        - mpv
        - mupdf
        - nmap
        - swayimg
        - unar
        - unzip
        - usbutils
        - wev
        - wiremix
        - wordgrinder

  - type: brew
    brew-analytics: false
    auto-update: true

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        install:
          - com.github.Matoking.protontricks
          - com.github.tchx84.Flatseal
          - io.github.wivrn.wivrn
          - com.valvesoftware.Steam
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
      - scope: user
        notify: false

  - type: fonts
    fonts:
      nerd-fonts:
      - JetBrainsMono
      - NerdFontsSymbolsOnly
      google-fonts:
      - Roboto
      - Open Sans
      - Inter

  - type: systemd
    system:
      enabled:
        - NetworkManager.service
    user:
      enabled:
        - pipewire.socket
        - wireplumber.service

  - type: script
    scripts:
      - setup-sway.sh
      # - install-yazi.sh
      - hardened-firefox.sh
      
    snippets:
      # Set zsh as default shell
      - sed -i 's/SHELL=\/bin\/bash/SHELL=\/usr\/bin\/zsh/' /etc/default/useradd
      - grep -q '/usr/bin/zsh' /etc/shells || echo '/usr/bin/zsh' >> /etc/shells

      # Append a loader to the end of the system-wide zshrc 
      - "echo 'for i in /etc/zsh/zshrc.d/*.zsh; do source \"$i\"; done' >> /etc/zshrc"

      # Forces Dracut to bundle the amdgpu driver AND activate your custom screen blanking module
      - echo -e 'add_drivers+=" amdgpu "\nadd_dracutmodules+=" plymouth-blank "' > /etc/dracut.conf.d/early-kms.conf

      # Completely blocks the Linux framebuffer from cycling the text cursor status
      - echo "w /sys/class/graphics/fbcon/cursor_blink - - - - 0" > /etc/tmpfiles.d/cursor_blink.conf

      # Set permissons of user scripts
      - "chmod +x /usr/bin/admin-autologin-set"
      - "chmod +x /usr/bin/admin-autologin-remove"
      
      # Forces the underlying GRUB templates to run completely silently
      #- sed -i 's/quiet_boot="0"/quiet_boot="1"/' /etc/grub.d/10_linux
      #- sed -i 's/echo "$(echo "Booting /true "/' /etc/grub.d/10_linux

      # Force wayland in flatpak
      #- flatpak override --global --env=ELECTRON_OZONE_PLATFORM_HINT=wayland com.brave.Browser

  - type: initramfs
 
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
