---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: MySway
description: Minimal Sway build that suits my needs.

base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      copr:
    install:
      # --- SYSTEM FOUNDATION ---
      - mesa-dri-drivers
      - NetworkManager
      - pipewire
      - policycoreutils
      - pipewire-pulseaudio
      - selinux-policy-targeted
      - wireplumber
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - xorg-x11-server-Xwayland

      # --- DESKTOP & UI ---
      - sddm
      - sddm-themes
      - sway
      - foot
      - fuzzel
      - swaybg
      - swayidle
      - swaylock
      - mako
      - wpaperd
      - swayosd
      - jetbrains-mono-fonts-all
      
      # --- SHELL & UTILS ---
      - zsh
      - stow
      - eza
      - zoxide
      - fzf
      - bat
      - ripgrep
      - fd-find
      - jq
      - htop
      
      # --- GRAPHICS & MEDIA ---
      - mpv
      - swayimg
      
      # --- HARDWARE & DEV ---
      - distrobox
      - openrgb-udev-rules
      - steam-devices
      - i2c-tools
      - solaar
      - xremap
      - dfu-util
      - dfu-programmer
      
      # --- MISC UTILS ---
      - aria2
      - bc
      - dash
      - file
      - gptfdisk
      - inxi
      - mupdf
      - nmap
      - progress
      - pulsemixer
      - termdown
      - tldr
      - trash-cli
      - unar
      - unzip
      - usbutils
      - wev
      - wl-clipboard
      - wl-color-picker
      - wlsunset
      - wordgrinder

  - type: default-flatpaks
    configurations:
      - scope: system # Installs for everyone; users cannot easily uninstall these
        install:
          - com.github.Matoking.protontricks
	        - com.github.tchx84.Flatseal
          - io.github.wivrn.wivrn
          - io.gitlab.librewolf-community
          - com.valvesoftware.Steam
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
      - scope: user # Ensures the Flathub repo is also ready for users to install their own apps

  - type: script
    snippets:
      - "systemctl enable sddm.service"
      - "systemctl enable NetworkManager.service"
      - "systemctl enable swayosd-libinput-backend.service"
      - "systemctl set-default graphical.target"
      - "systemctl enable swayosd-libinput-backend.service"
      - "systemctl --global enable pipewire.socket"
      - "systemctl --global enable wireplumber.service"
	  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
