# Set global default shell to Zsh for all users
set-option -g default-shell /usr/bin/zsh

# Enable mouse support (allows scrolling with the mouse wheel)
set -g mouse on

# Use PageUp to enter copy mode directly
bind-key -n PPage copy-mode -u

# Use Vi-style keys in copy mode (better for zsh/vim users)
setw -g mode-keys vi
